language: node_js
node_js:
  - "node"
  - "stable"
cache: npm
install:
  - npm ci
script:
  - npm test
  - npm run lint
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
